services:
  ingest:
#    build: ./app/
    command: python -m providers.ingest
    runtime: nvidia
    image: event-planner-rag:latest
    volumes:
      - ./app:/app               # код
      - qdrant_data:/app/qdrant_db  # общие данные Qdrant
    environment:
      - QDRANT_PATH=/app/qdrant_db
      - MODEL_DIR=/opt/models/my_model
      - EMBEDDINGS_MODEL_NAME=/opt/embeddings/e5_base


  app:
    command: python api.py
    runtime: nvidia
    depends_on:
      ingest:
        condition: service_completed_successfully
    image: event-planner-rag:latest
    volumes:
      - ./app:/app
      - qdrant_data:/app/qdrant_db
    environment:
      - QDRANT_PATH=/app/qdrant_db
      - MODEL_DIR=/opt/models/my_model
      - EMBEDDINGS_MODEL_NAME=/opt/embeddings/e5_base
    ports:
      - "8080:8080"
volumes:
  qdrant_data:

